server:
  port: 8081
  error:
    include-message: always

isActive: true

spring:
  application:
    name: Hackathon
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/user_db
#    password: root
    username: beinstance
    url: jdbc:mysql://google/navigators?cloudSqlInstance=hackathon-be-project:asia-south1:beinstance&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.MySQL8Dialect
